// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2m2znYRc5wjGArC-8J1kTbYzcdnkq9Sk',
    appId: '1:590022833338:web:e98a28488dfc5985dd7e83',
    messagingSenderId: '590022833338',
    projectId: 'sihwomen1-1',
    authDomain: 'sihwomen1-1.firebaseapp.com',
    storageBucket: 'sihwomen1-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfM4GAsBdpdGkrxDO6XQUApX1uZDs3TKw',
    appId: '1:590022833338:android:847093e0c14a498fdd7e83',
    messagingSenderId: '590022833338',
    projectId: 'sihwomen1-1',
    storageBucket: 'sihwomen1-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGTvnvCiNSdlhrebFWjxmVsKzYPR4HI7k',
    appId: '1:590022833338:ios:94353f245067643bdd7e83',
    messagingSenderId: '590022833338',
    projectId: 'sihwomen1-1',
    storageBucket: 'sihwomen1-1.appspot.com',
    iosBundleId: 'com.example.sihwomen1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGTvnvCiNSdlhrebFWjxmVsKzYPR4HI7k',
    appId: '1:590022833338:ios:2c0099255fc1ad77dd7e83',
    messagingSenderId: '590022833338',
    projectId: 'sihwomen1-1',
    storageBucket: 'sihwomen1-1.appspot.com',
    iosBundleId: 'com.example.sihwomen1.RunnerTests',
  );
}
